# Generated by Django 5.0 on 2024-01-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatime', '0003_tea'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
