# Generated by Django 5.0 on 2024-01-12 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatime', '0004_profile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tea_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
